### ISSUE TITLE
Releases are confusing

### ISSUE THREAD

**Issue by luizluca** [OpenNMS/jrrd2#2]
Hello,

On jrrd2 releases, I see 2.0.3 marked as the "latest", but also 2.0.4 and 2.0.5 (and 2.0.5 is older than 2.0.4)
.
Something is wrong here.

Could you please clarify?

**Comment by RangerRick** [comment]
2.0.4 is "newer" because I realized while packaging 2.0.5 that I forgot to tag 2.0.4.

The general disarray of releases is because I remember to tag, but forget to go into github to actually turn the tag into a release.  ;)

We generally have not kept up well with tracking ancillary OpenNMS tools like JRRD2 but I'll endeavor to handle it better in the future.

**Comment by RangerRick** [comment]
And actually now that I look at it, I never *did* package 2.0.5, it's just some wrong tag I made, I guess?  Anyways, I've removed it altogether now.  :)
