### ISSUE TITLE
[IMP]: Avoid maven for building packages

### ISSUE THREAD

**Issue by luizluca** [OpenNMS/jrrd2#4]
Hello,

Maven is not a very "package build system" friendly. Normally a "package build system" does not even provide internet access (which is almost a requirement for maven).

If possible, could you include maven-generated files and/or replace buidling jar with standard tools? I guess only the JNI part really needs to be built specific for each system.

**Comment by RangerRick** [comment]
Since we a) want to deploy it to maven central and b) depend on at least one external library (SLF4J) changing the build is not really feasible (unless it's doing something else in *addition* which is kind of silly...)

Maven really _is_ the "standard tool" for Java-with-dependencies, unless we were to move to gradle (which still relies on maven repositories in the end).

**Comment by luizluca** [comment]
Thanks @RangerRick ,

I'm starting to deal better now with maven. The process is something like:

1) predownload all maven deps for the project (#3 makes this very difficult)
2) pack deps as a source
3) unpack on %prep
4) reconfigure maven to use this local repo (MAVEN_OPTS="-Dmaven.repo.local=/xxx")

It is still not great but, at least, it works ;-)
